# Generated by Django 2.2.3 on 2019-07-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='slug',
            field=models.CharField(default='Tgn44KWo2D', max_length=10),
        ),
    ]
