# Generated by Django 2.2.3 on 2019-07-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pasties', '0002_auto_20190716_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='slug',
            field=models.CharField(default='hVwNuRZKGo', max_length=10),
        ),
    ]
